common: &common
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 1
  username: root
  password:

#----------------------------------------------------------------
development:
  <<: *common
  database: db_charmer_sandbox_development
  
  # logs database
  logs:
    <<: *common
    database: db_charmer_logs_development
    dump: true

  # logs database
  slave01:
    <<: *common
    username: db_charmer_ro
    database: db_charmer_sandbox_development

#----------------------------------------------------------------
test:
  <<: *common
  database: db_charmer_sandbox_test

  # logs database
  logs:
    <<: *common
    database: db_charmer_logs_test
    dump: true

  # logs database
  slave01:
    <<: *common
    username: db_charmer_ro
    database: db_charmer_sandbox_test

#----------------------------------------------------------------
production:
  <<: *common
  database: db_charmer_sandbox_production

  # logs database
  logs:
    <<: *common
    database: db_charmer_logs_production
    dump: true

  # logs database
  slave01:
    <<: *common
    username: db_charmer_ro
    database: db_charmer_sandbox_production
